name: Lint Code Base

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # update checkout too

      - name: Run Super Linter
        uses: super-linter/super-linter/slim@v6.0.0  # latest release
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
